### PR TITLE
NetAM ARM generation

### PR DESCRIPTION
**Pull request by xi-yang**
Attached is the latest model generated by the script. Note that after adding stitch_node=True everywhere, we see no delegation in the model now. Not sure if that is expected. 

[network-arm.graphml.txt](https://github.com/fabric-testbed/information-model-utils/files/6587337/network-arm.graphml.txt)

### CODE REVIEW

**Comment by xi-yang** [comment]
@ibaldin I pushed the `nstype` change. The latest fim 0.50 is giving me an error. Looks like some changes need to be merged to the main branch for FIM. I will provide a graphml when this is fixed.

`ImportError: cannot import name 'NSLayer' from 'fim.slivers.switch_fabric' (/Users/xiyang/.virtualenvs/information-model-utils/lib/python3.9/site-packages/fim/slivers/switch_fabric.py)`

**Comment by ibaldin** [comment]
This change to requirements should fix the problem

**Comment by xi-yang** [comment]
FIM 0.52 fixed the problem. @ibaldin please review the attached model. 
[network-arm.graphml.txt](https://github.com/fabric-testbed/information-model-utils/files/6600649/network-arm.graphml.txt)

**Comment by xi-yang** [comment]
@ibaldin This is the latest netam ARM with restored delegation on interfaces. 

[network-arm.graphml.2021-06-14.txt](https://github.com/fabric-testbed/information-model-utils/files/6649658/network-arm.graphml.2021-06-14.txt)

**Review by ibaldin — APPROVED** [review]

**Comment by xi-yang** [comment]
@ibaldin Here goes with some fixes based on your June 18 Slack comments. 
[network-arm.graphml.2021-06-21.txt](https://github.com/fabric-testbed/information-model-utils/files/6687350/network-arm.graphml.2021-06-21.txt)

**Pull request merged**
