### PR TITLE
add --skip_device option for scan_net

### PR DESCRIPTION
**Pull request by xi-yang**
When some device has no isis interface configured and we still want to scan, this patch will firstly report an error. Then we can use the --skip-device option to skip one or multiple devices. 

Devices without p2p links configured in NetworkController inventory will be skipped as well.

### CODE REVIEW

**Review by ibaldin — APPROVED** [review]
+1

**Comment by ibaldin** [comment]
@xi-yang all commits are unsigned :-(

**Comment by ibaldin** [comment]
I take it back - I think they are signed, but GitHub doesn't have the public key to verify them.

**Comment by xi-yang** [comment]
Somehow my last key uploaded was an already expired. Fixed.

**Pull request merged**
